language: c
env:
  global:
    - ARDUINO_VERSION=1.8.9
  matrix:
    - BOARD="esp8266:esp8266:d1_mini:xtal=80,eesz=4M3M,ip=lm2f,exception=disabled"
    - BOARD="esp32:esp32:widora-air:FlashFreq=80"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$ARDUINO_VERSION-linux64.tar.xz
  - tar xf arduino-$ARDUINO_VERSION-linux64.tar.xz
  - sudo mv arduino-$ARDUINO_VERSION /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/IotWebConf
  - arduino --install-library "MQTT"
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json,https://dl.espressif.com/dl/package_esp32_index.json" --save-prefs
  - if [[ "$BOARD" =~ "esp8266:esp8266:" ]]; then
      arduino --install-boards esp8266:esp8266;
    fi
  - if [[ "$BOARD" =~ "esp32:esp32:" ]]; then
      arduino --install-boards esp32:esp32;
    fi
script:
   - arduino --verify --board $BOARD examples/IoTWebConf_for_Visuino_modified_by_IoT_Jedi01Minimal/IoTWebConf_for_Visuino_modified_by_IoT_Jedi01Minimal.ino
   - arduino --verify --board $BOARD examples/IoTWebConf_for_Visuino_modified_by_IoT_Jedi02StatusAndReset/IoTWebConf_for_Visuino_modified_by_IoT_Jedi02StatusAndReset.ino
   - arduino --verify --board $BOARD examples/IoTWebConf_for_Visuino_modified_by_IoT_Jedi03CustomParameters/IoTWebConf_for_Visuino_modified_by_IoT_Jedi03CustomParameters.ino
   - arduino --verify --board $BOARD examples/IoTWebConf_for_Visuino_modified_by_IoT_Jedi04UpdateServer/IoTWebConf_for_Visuino_modified_by_IoT_Jedi04UpdateServer.ino
   - arduino --verify --board $BOARD examples/IoTWebConf_for_Visuino_modified_by_IoT_Jedi05Callbacks/IoTWebConf_for_Visuino_modified_by_IoT_Jedi05Callbacks.ino
   - arduino --verify --board $BOARD examples/IoTWebConf_for_Visuino_modified_by_IoT_Jedi06MqttApp/IoTWebConf_for_Visuino_modified_by_IoT_Jedi06MqttApp.ino
   - arduino --verify --board $BOARD examples/IoTWebConf_for_Visuino_modified_by_IoT_Jedi07MqttRelay/IoTWebConf_for_Visuino_modified_by_IoT_Jedi07MqttRelay.ino
   - arduino --verify --board $BOARD examples/IoTWebConf_for_Visuino_modified_by_IoT_Jedi08WebRelay/IoTWebConf_for_Visuino_modified_by_IoT_Jedi08WebRelay.ino
   - arduino --verify --board $BOARD examples/IoTWebConf_for_Visuino_modified_by_IoT_Jedi09CustomConnection/IoTWebConf_for_Visuino_modified_by_IoT_Jedi09CustomConnection.ino
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: change
    on_failure: change
